# This is a basic workflow to help you get started with Actions

name: springmusic

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: create directory 
      run: |
        mkdir ./japp
    - uses: actions/download-artifact@v2
      with:
        name: springmusic
        path: ./japp/
    - name: Checkout
      uses: actions/checkout@v2
    - name: validate downloaded file 
      run: |
        ls -al
        ls -al ./japp
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: dshivakumar/japp:latest
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    - name: Run Commands
      run: |
        ls -al ./build/libs
    - uses: actions/upload-artifact@v2
      with:
        name: springmusic
        path: ./build/libs/spring-music-1.0.jar
